language: bash
os: linux
#virt: vm
#dist: precise

rvm:
  2.5

env:
  global:


install:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install jekyll
#  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install liquid

before_install:
  - gem update --system
  - gem --version

build:
  - sudo /bin/sh -c build.sh

before_deploy:
#  - sudo jekyll b --trace
  - gem update --system
  - gem --version

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true

  - sudo jekyll s --trace

  on:
    branch: gh-pages

branches:
    only:
    - gh-pages
