language: bash
os: linux
#virt: vm
#dist: xenial

rvm:
  2.5

env:
  global:


nstall:
  - sudo apt-get install perl5
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install jkelly

build:
  - sudo /bin/sh -c build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true

  #- sudo /bin/sh -c perl -v

  on:
    branch: gh-pages


branches:
    only:
    - gh-pages
