{
  "build": [
    "sudo /bin/sh -c build.sh"
  ],
  "language": "shell",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "rvm": [
    "2.5"
  ],
  "env": {
    "global": [
      {}
    ]
  },
  "deploy": [
    {
      "provider": "pages",
      "strategy": "git",
      "skip_cleanup": true,
      "keep_history": true,
      "on": {
        "branch": [
          "gh-pages"
        ]
      },
      "token": "$GITHUB_TOKEN"
    }
  ],
  "branches": {
    "only": [
      "gh-pages"
    ]
  }
}
