language: bash
os: linux
#virt: vm
dist: xenial

rvm:
  2.5

env:
  global:


install:
  - sudo apt-get install perl5

before_install:
  - sudo /bin/sh -c which perl && sudo perl -v

build:
  - sudo /bin/sh -c build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true

  - sudo /bin/sh -c perl -v

  on:
    branch: gh-pages


branches:
    only:
    - gh-pages
