language: bash

env:
  global:
    secure: j1Cd7pgx6JLX02LpXwBTxz9TQKaUyfdB9sjW78EpMQOhMwVgAXZX90KSDHVtEC07IVLBYbl5YTfIkLFNqfIHykFbXGGINJFTxxEZHOFJ2dYi7h4a5mGUK/MbTPQw8bNm08rymdECAwnc/zl/YpOlhkBSvxDyfOkhFBxX2v6kFwwVNJ5VIOyrSEbnN8ZfWgOqfpBn4oI+j8BBZOx5qPvEaL4GepNC6tE3B1FdLIOIIfwYYuutG8pyofbB9HC+0MyCOQILJXsG2uhRj2sCcfblXnzkONAdimjRii5lYbDUm4brcsOw91yp8HgbIQQ2thMFBOtOmeyTr6AhPI15gzd7kZPSNnYYfNJk2uq2nra1Ld/yiSDEzM9KLmCKhG96R0Hur63Ng68tSjBcON7VMaF056IjLTd975gES4PskoYtbwlyBPylvhTfJ7E8pSygqWqVr4XcZJ4GuAD7CnL3FJXUdrb6JEPONErSvjHmyX/LvrNM1GULlTz8Tk7duTX+XaIBwmm+Q4Sw6UAKzuPc2olf0vQBeDcx2ouzYLXjDl+ZfR1mDp8EN2giiSu1Cz0uqX492KjL8ukAmqhMEpFQdD5DLq7yeEZcYAjLGJs6y746guHkx3RmKueF6rYudvW+JsR+onvjEo2JpCiobsaIDdyqTUj0EYSjHjP3+bfqrpr++18=

build:
  script:
  - bash build.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  script:
  - perl -e 'system("sudo killall apt-get");'
