#!/usr/bin/env ruby2.5
language: ruby
os: linux
dist: xenial

rvm:
  2.5


#########################

jobs:
  build:
    name: "build1"
    command: |


    name: "build2"
    command: |


#########################

test1:


test2:


#########################

install:


before_install:


#########################

build:

  on:
    branch: gh-pages

#########################

before_deploy:


deploy:


  on:
    branch: gh-pages

branches:
    only:
    - gh-pages

