# config.yml
version: 2.1
jobs:
  main:
    machine: true
    steps:
      - checkout
#      - run:
#          command: echo "building"
#      - run:
#          command: echo "testing"
#      - run:
#          command: bash build.sh

workflows:
  build:
    jobs:
      - main:
          pre-steps:
#            - run:
#                command: echo "prepared"
          post-steps:
#            - run:
#                command: echo "build stage"
#            - run:
#                command: echo "build done"
            - run:
                command: bash build.sh

#            - run:
#                name: Deploy Over SSH
#                command: |
#                  ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
