# config.yml
version: 2.1
os: linux
#virt: vm
dist: ubuntu
rvm:
  2.5

jobs:
  main:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y install build-essential
            sudo apt-get -y upgrade

      - run:
          command: |
            sudo apt-get -y install ddate
            sudo apt-get -y install aptitude


workflows:
  version: 2
  build:
    jobs:
      - main:
          pre-steps:
            - run:
                command: /bin/sh -v
          post-steps:
#            - run:
#                command: echo "build stage"
#            - run:
#                command: echo "build done"
            - run:
                command: sudo /bin/sh -c build.sh

#            - run:
#                name: Deploy Over SSH
#                command: |
#                  ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
    on:
      branch: gh-pages

branches:
  only:
  - gh-pages
  - "/.*/"
