language: bash
os: linux
#virt: vm
dist: xenial

rvm:
  2.5

env:
  global:

jobs:
  build:
    run:
      name: "build"
      command: |
#        sudo jekyll cleanup
#        sudo jekyll b --trace
  test:
    run:
      name: none

install:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install ext
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install bundler
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install jekyll

before_install:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install what_you_mean
  - gem update --system
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem update


build:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem update


before_deploy:
  - gem update --system
  - gem --version

deploy:
##  github_token: GITHUB_TOKEN

  - /bin/sh -c build.sh
  on:
    branch: gh-pages

branches:
    only:
    - gh-pages

