language: bash
os: linux
#virt: vm
dist: xenial

rvm:
  2.5

env:
  global:

jobs:
  build:
    run:
      name: somewhat
      #command: echo moo
  test:
    run:
      name: none

install:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install what_you_mean
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install bundler
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl

before_install:
  - gem update --system
  - gem --version

build:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem update
  - sudo /bin/sh -c build.sh

before_deploy:
  - gem update --system
  - gem --version

deploy:
##  github_token: GITHUB_TOKEN

  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install bundler

  on:
    branch: gh-pages

branches:
    only:
    - gh-pages

