# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: RunnerOne
email: RunnerOne@Runner.One
description: >- # this means to ignore newlines until "baseurl:"
  Just a kind of some starter project for Github Actions testing purposes.
  Can be labelled as template for future projects including Github Pages
  uses Jekyll as static site generator. Produced rendered default pages
  over CI workflow.
baseurl: "/runner_one" # the subpath of your site, e.g. /blog
url: "https://wryyyyyyyy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#####################################

#####################################
source              : .
destination         : _site
collections_dir     : _collection
plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir          : _sass
collections:
  posts:
    output          : true
    permalink       : /posts/:year/:month/:day/:title/
  commits:
    output          : true
    permalink       : /commits/:year/:month/:day/:title/
  drafts:
    output          : true
    permalink       : /drafts/:title/
  notes:
    output          : true
    permalink       : /notes/:year/:month/:day/:title/
  pages:
    output          : true
    permalink       : /pages/:year/:month/:day/:title/
  logs:
    output          : true
    permalink       : /logs/:year/:month/:day/:title/

markdown: kramdown

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-commonmark-ghpages
  - github-pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
