name: CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install bundler
        run: |
          sudo gem install bundler
          bundle install

      - name: Prepare post
        run: |
          export logdata=`date '+%Y-%m-%d'`
          export logfile=`git log -1 --format='%H'`
          echo "---" > docs/_collection/_posts/_commits/$logdata-commit-$logfile.md
          echo "layout: post" >> docs/_collection/_posts/_commits/$logdata-commit-$logfile.md
          echo "title: $logdata-commit-$logfile" >> docs/_collection/_posts/_commits/$logdata-commit-$logfile.md
          echo "tags: commit $logfile" >> docs/_collection/_posts/_commits/$logdata-commit-$logfile.md
          echo "---" >> docs/_collection/_posts/_commits/$logdata-commit-$logfile.md
          echo "" >> docs/_collection/_posts/_commits/$logdata-commit-$logfile.md
          git log -1 >> docs/_collection/_posts/_commits/$logdata-commit-$logfile.md

      - name: Build site
        run: |
          cd docs
          bundle exec jekyll b --trace --incremental
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
