name: CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install bundler
        run: |
          sudo gem install bundler
          bundle install

      - name: Build site
        run: |
          cd docs
          export logdata=`date '+%Y-%m-%d'`
          export logfile=`git log -1 --format='%H'`
          echo "---" > ./_posts/$logdata-$logfile.md
          echo title: "$logfile" >> ./_posts/$logdata-$logfile.md
          echo layout: post >> ./_posts/$logdata-$logfile.md
          echo "---" >> ./_posts/$logdata-$logfile.md
          echo "" >> ./_posts/$logdata-$logfile.md
          git log -1 >> ./_posts/$logdata-$logfile.md
          bundle exec jekyll b --trace
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
