name: CI

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install bundler
        run: |
          sudo gem install bundler
          bundle install

      - name: Build site
        run: |
          cd docs
          export logfile=`git log -1 --format='%H'`.md
          touch _posts/$logfile
          git log -1 > _posts/$logfile
          bundle exec jekyll b --trace
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
