name: deploy
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo gem install bundler
    - run: bundle install
    - run: cd docs && bundle exec jekyll b --trace #--watch --incremental
