# Name of the workflow
name: github pages deployment

# Controls when the action will run. Triggers the workflow on
# push or pull request events but only for the dev branch
on:
  push:
    #branches: [ dev ]
  pull_request:
    #branches: [ dev ]

# Specifies what to run on the trigger
jobs:
  deploy:
#    runs-on: xenial
    steps:
    # first we need to checkout the repo
    # if dev brach is not the default branch
    # then you can specify the branch with 'ref'
    - uses: actions/checkout@v3
    # then setup nodejs on the machine
    #- uses: actions/setup-node@v1
    #  with:
    #    node-version: '12'

    # then we need to install our static site generator
    #- run: npm install -g gatsby-cli
    # doing clean install
    #- run: npm ci

    # Building the site (static web pages)
    #- name: Gatsby Build
    #  run: gatsby build

    # Copy all files from the build folder to the master branch
    #- name: Deploy
    #  uses: peaceiris/actions-gh-pages@v3
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    publish_dir: ./public
    #    publish_branch: master  # deploying branch
#on:
#  push:
#    paths:
#    - '**version.txt'
